apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-dev-pvc
  namespace: xgboost-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dev
  namespace: xgboost-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dev
  template:
    metadata:
      labels:
        app: postgres-dev
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: xgboost-secrets
              key: DB_PASSWORD
        - name: POSTGRES_DB
          value: "octagona"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-dev-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-dev
  namespace: xgboost-dev
spec:
  type: NodePort
  selector:
    app: postgres-dev
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30434
